spring:
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    metadata-map:
      zone: primary
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: primary
